name: CI

on:
  push:
    paths-ignore:
      - "README.md"
      - "docs/readme.md"
      - "docs/readme.rst"
  pull_request:
    paths-ignore:
      - "README.md"
      - "docs/readme.md"
      - "docs/readme.rst"
  release:
    types: [published]

jobs:
  tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install pip -U
          pip install tox codecov
      - name: Set TOXENV
        run: |
          python_version="${{ matrix.python-version }}"
          py_version="${python_version/./}"
          TOXENV="py$py_version"
          echo $TOXENV
          echo "TOXENV=$TOXENV" >> $GITHUB_ENV
      - name: Run tox
        run: tox
      - name: Upload coverage report
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
          verbose: true
  pre-commit:
    name: Run pre-commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install pip -U
          pip install tox
      - name: Run pre-commit
        env:
          TOXENV: pre-commit
        run: tox
  check-version:
    name: Check version
    # only for PRs in master
    if: ${{ github.base_ref == 'master' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get current version
        id: currentVersion
        uses: mikefarah/yq@master
        with:
          cmd: yq e ".metadata.template_version" shell-definition.yaml
      - name: Save shell-definition.yaml from master
        run: |
          git clone https://github.com/${{ github.repository }}.git ${{ github.repository }}
          BASE_DIR=`pwd`
          cd ${{ github.repository }}
          git checkout -qf ${{ github.head_ref }}
          git show master:shell-definition.yaml > $BASE_DIR/tmp.yaml
      - name: Get master version
        id: masterVersion
        uses: mikefarah/yq@master
        with:
          cmd: yq e ".metadata.template_version" tmp.yaml
      - name: Check version
        run: |
          ! diff <(echo "${{ steps.currentVersion.outputs.result }}") <(echo "${{ steps.masterVersion.outputs.result }}")
  create-gh-release:
    needs: [ tests, pre-commit ]
    if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set envs
        run: |
          version="$(cat version.txt | tr -d ' \t\n\r')"
          repo_owner=${{ github.repository }}
          index=`expr index "$repo_owner" /`
          repo=${repo_owner:index}
          echo "TAG=$version" >> $GITHUB_ENV
          echo "REPO=$repo" >> $GITHUB_ENV
      - name: Create GitHub release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          name: ${{ env.REPO }} ${{ env.TAG }}
          tag: ${{ env.TAG }}
          commit: master
